author:       'Washington Botelho'
description:  'Se você não tem dom, tenha vontade!'
email:        'wbotelhos@gmail.com'
nick:         'wbotelhos'
url:          'wbotelhos.com.br'
url_http:     'http://wbotelhos.com.br'
url_www:      'www.wbotelhos.com.br'
year:         '2012'
